tasks:
  - before: rustup component add clippy
    init: |
      cargo update
      cargo clippy --all-features
      cargo doc --all-features --no-deps
      cargo test --all-features
      cargo test --no-default-features
    command: cargo watch -x test

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: false
